### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by ramifygames** [arboleya/electrify#12]
Thank you for this! I was able to get your method to work more easily than others.  I can build an app just fine (I'm on Windows 10), but I can't figure out how to set the icon.  Only thing I knew to try was adding "icon":"myfileName.ico" to the .electrify/package.json object.  And, I've tried it with the image file in the root folder and the .electrify folder, if that matters.  I wasn't sure.

**Comment by arboleya** [comment]
Hi @ramify, glad the `no learning curve` slogan is kinda standing to its point. :)

About the icon, currently there's no way to pass arguments to electron-packager.

I'm wondering if it really worths  to keep the packaging step embedded in Electrify. Perhaps it's better to keep just the built step outputting a compliant Electron project, so everyone can fully customize it by using `electron-packager` itself -- It's pretty much the way Meteor handles iOS and Android apps if I'm not wrong.

Temporarily, you can do this like this:
1. First release it first with `electrify`
2. Then remove the `.electrify/.dist` folder
3. Package your app (`.electrify`) manually with [electron-packager](https://github.com/maxogden/electron-packager) -- since after removing the `.dist` folder, the `.electrify` folder should be a fully-compliant Electron project

Thanks for reporting.

**Comment by arboleya** [comment]
Btw, I'll let you know when I have a proper solution for this.

**Comment by ramifygames** [comment]
Awesome, thanks.  I'm very new to these technologies, so I don't know what I'm talking about, but I personally didn't mind not having other packaging options.  I like not having to read a lot of documentation and just running a simple command or 2 to make a bunch of stuff happen, ha.  (That's why I think Meteor's so cool)  But, I'll be working on my app for a while still before actually needing to package it anyway.  I was just seeing what's out there ahead of time.

**Comment by arboleya** [comment]
@ramify Implemented in `2.0.0`, check out the new API / usage in project README.

Package options here:
https://github.com/arboleya/electrify#packaging

Check the Electron Packager options.
