### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by zimt28** [arboleya/electrify#13]
Hey there!
Thanks for this package, it makes creating desktop apps so simple!
I have some questions, hope you're ok with me not opening a bunch of issues :D
- Do you have a roadmap? If so, can you share it?
- Is there a way to work with menus?
- Is it possible to create an app which is just a client? electrify seems to bundle a Meteor server as well

Thanks again, great work!

**Comment by arboleya** [comment]
Hi there!

Lets answer your questions:
1. Not yet, however I'm in the middle of a refactoring to make the code more maintainable and testable -- testing things manually in a cross-platform way is awful. After this, I'll move on and put up a Roadmap, but I can tell that I'm looking forward to:
   - Provide a simple plugin architecture for easy expansion of functionalities
   - Provide options to build server+client or just the client (connecting to a remote host)
   - Provide integration between Meteor's server and Electron API through plugins **this one will require further research**
2. Not currently. I mean, you can do whatever you want inside the `.electrify` directory, it's a plain Electron project. But there's no current channel of communication between Meteor's server and Electron API. Probably you'd want to manually build a socket channel between Electron x Meteor, as I've suggested this approach here #9 as well
3. Yes but you'll have to dig a little and figure out the way -- however as I said I imagine it will be possible through plugins, but it will require further analysis, i.e. define which one (server or client) will have acess to Electron, or both. There's some things that need a closer look before anything else.

**Comment by greatramu** [comment]
hello! Firstly, super cool project. Keep the momentum :+1: 

It would be very helpful to have a sample project/guide on setting up connection between server and electron build

**Comment by arboleya** [comment]
Hi @greatramu, thanks and sorry for the huge delay.

Just to let you know, I'm working with the plugins API and I see this as another plugin in the stack (as mongo, nodejs etc). Without a proper API it would require lots of hacking to get it to work _effectively_.

However, as I've said, besides the plugins api this question itself requires further research because there's various scenarios of how and where this communication should be established. 

I myself will have to dig a little into this topic, anyway it should be out sooner than later.

Stay tuned.

**Comment by arboleya** [comment]
Implemented in `2.0.0`.

Check the project README for more info:
https://github.com/arboleya/electrify#meteor-x-electron-integration
